name: Publish Resume in JSONResume format as Github Page
 
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
        with:
         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
      - 
        uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: macchiato
          resume_filepath: resume.json
          output_filepath: docs/index.html
      - 
        name: "Deploy to Pages"
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: docs/  # <- Dossier contenant notre documentation générée
          BRANCH: publish     # <- Branche sur laquelle seront commités les fichiers
